spring.application.name=skillsync
ai.base-url=ai.service.url=${AI_SERVICE_URL}

spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync
spring.datasource.username=evansanderson
spring.datasource.password=skillsync123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=
spring.datasource.driver-class-name=
spring.jpa.hibernate.ddl-auto=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration